{% set name = "perl-db_file" %}
{% set version = "1.857" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/DB_File-{{ version }}.tar.gz
  sha256: 7528eaee49ccd3de268d9358226c6c7617d0d7d8786fcc31d7402c54d570a394

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - perl
    - libdb

  run:
    - perl

test:
  imports:
    - DB_File

about:
  home: https://metacpan.org/pod/DB_File
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  license_file: LICENSE.txt
  summary: DB_File is a module which allows Perl programs to make use of the facilities provided by Berkeley DB
  dev_url: https://github.com/pmqs/DB_File

extra:
  recipe-maintainers:
    - rpetit3
